# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eew_parser}
  s.version = "0.1.6"

  s.authors = ["Masaki Matsushita"]
  s.date = %q{2014-12-28}
  s.description = %q{Parser for Earthquake Early Warning from JMA}
  s.email = %q{glass.saga@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "eew_parser.gemspec",
    "lib/eew_parser.rb"
  ]
  s.homepage = %q{http://github.com/Glasssaga/eew_parser}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.summary = %q{parser for Earthquake Early Warning}
end
